# Generated by Django 4.1 on 2024-05-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=75)),
                ('team_abbr', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GameOdds',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('home_h2h_price', models.IntegerField()),
                ('home_spread_price', models.IntegerField()),
                ('home_spread_point', models.FloatField()),
                ('away_h2h_price', models.IntegerField()),
                ('away_spread_price', models.IntegerField()),
                ('away_spread_point', models.FloatField()),
                ('over_price', models.IntegerField()),
                ('over_point', models.FloatField()),
                ('under_price', models.IntegerField()),
                ('under_point', models.FloatField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='NBAapp.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='NBAapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='BoxScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team1_q1_points', models.IntegerField()),
                ('team1_q2_points', models.IntegerField()),
                ('team1_q3_points', models.IntegerField()),
                ('team1_q4_points', models.IntegerField()),
                ('team1_total', models.IntegerField()),
                ('team2_q1_points', models.IntegerField()),
                ('team2_q2_points', models.IntegerField()),
                ('team2_q3_points', models.IntegerField()),
                ('team2_q4_points', models.IntegerField()),
                ('team2_total', models.IntegerField()),
                ('team1_pace', models.FloatField()),
                ('team1_efg', models.FloatField()),
                ('team1_tov', models.FloatField()),
                ('team1_orb', models.FloatField()),
                ('team1_ft_per_fg', models.FloatField()),
                ('team1_off_rtg', models.FloatField()),
                ('team2_pace', models.FloatField()),
                ('team2_efg', models.FloatField()),
                ('team2_tov', models.FloatField()),
                ('team2_orb', models.FloatField()),
                ('team2_ft_per_fg', models.FloatField()),
                ('team2_off_rtg', models.FloatField()),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='NBAapp.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='NBAapp.team')),
            ],
        ),
    ]
