# Generated by Django 4.1 on 2024-05-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAapp', '0002_alter_boxscore_date_gameodds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxscore',
            name='date',
            field=models.DateField(),
        ),
    ]
