# Generated by Django 4.1 on 2024-05-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBAapp', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('prop', models.CharField(max_length=40)),
                ('over_under', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('point', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAapp.gameodds')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAapp.player')),
            ],
        ),
    ]
