# Generated by Django 4.1 on 2024-05-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAapp', '0003_alter_boxscore_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxscore',
            name='team1_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxscore',
            name='team2_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
