# Generated by Django 4.1 on 2024-05-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAapp', '0003_playerodds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerodds',
            name='point',
        ),
        migrations.RemoveField(
            model_name='playerodds',
            name='price',
        ),
        migrations.RemoveField(
            model_name='playerodds',
            name='prop',
        ),
        migrations.AddField(
            model_name='playerodds',
            name='assists_point',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='assists_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='last_update',
            field=models.DateTimeField(default='2024-05-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerodds',
            name='points_assists_point',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='points_assists_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='points_point',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='points_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='points_rebounds_assists_point',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='points_rebounds_assists_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='rebounds_point',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='rebounds_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='threes_point',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerodds',
            name='threes_price',
            field=models.IntegerField(default=0),
        ),
    ]
